version: "3"
services: 
    app:
        restart: always
        build: 
            context: .
            dockerfile: Dockerfile
        container_name: app
        env_file: .env.prod
        ports: 
            - "$PORT:$PORT"
        depends_on: 
            - mysql
    
    mysql:
        image: mysql
        container_name: mysql
        restart: always
        env_file: .env.mysql
        security_opt:
            - seccomp:unconfined
        ports: 
            - '3306:3306'